export const userLanguagesSx = {
  sectionTitle: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: "none",
    mb: 3,
  },
  mainColumn: {
    display: "flex",
    flexDirection: "column",
    minHeight: 280,
  },
  languagesRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 6,
    rowGap: 4,
    flex: 1,
    py: 2,
    listStyle: "none",
    m: 0,
    p: 0,
  },
  languageListItem: {
    listStyle: "none",
  },
  languageEntryClickable: {
    border: "2px solid transparent",
    padding: 0,
    margin: 0,
    background: "transparent",
    cursor: "pointer",
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    borderRadius: 1,
    font: "inherit",
    color: "inherit",
    textAlign: "left",
    py: 1,
    px: 1.5,
    mx: -0.5,
    "&:hover": {
      bgcolor: "rgba(255,255,255,0.06)",
    },
    "&:focus-visible": {
      outline: "2px solid #df4d4d",
      outlineOffset: 2,
    },
  },
  languageEntryClickableSelected: {
    borderColor: "#df4d4d",
    bgcolor: "rgba(223,77,77,0.12)",
    "&:hover": {
      bgcolor: "rgba(223,77,77,0.16)",
    },
  },
  languageEntryStatic: {
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    py: 1,
    px: 1.5,
  },
  proficiencyLearner: {
    color: "#6fcf97",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  proficiencyNative: {
    color: "#df4d4d",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  languageName: {
    color: "var(--app-text-muted)",
    fontSize: 18,
    fontWeight: 400,
  },
  actionsRow: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 3,
    flexWrap: "wrap",
    mt: "auto",
    pt: 3,
    pr: { xs: 4, sm: 8 },
    pl: 0,
  },
  addLanguageBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "var(--app-text-muted)",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "var(--app-text)",
    },
  },
  removeLanguagesBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "#df4d4d",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "#ef6d6d",
    },
  },
  emptyState: {
    color: "var(--app-text-muted)",
    fontSize: 15,
    textAlign: "center",
    py: 4,
  },
  errorText: {
    color: "#ffb4b4",
    fontSize: 14,
  },
  languageDialog: {
    "& .MuiDialog-paper": {
      bgcolor: "var(--app-surface)",
      backgroundImage: "none",
      borderRadius: 2,
      maxWidth: 440,
      width: "100%",
    },
  },
  /** Wider paper for Add language so labels and select values are not clipped. */
  addLanguageDialog: {
    "& .MuiDialog-paper": {
      maxWidth: 560,
    },
  },
  dialogTitleRoot: {
    m: 0,
    p: 0,
    px: 3,
    pt: 2,
  },
  /** Extra space below the title in the Add language dialog only. */
  addLanguageDialogTitleRoot: {
    m: 0,
    p: 0,
    px: 3,
    pt: 2,
    mb: 2.5,
  },
  dialogTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
    pr: 0.5,
    pt: 1,
    pb: 0.5,
  },
  dialogTitleText: {
    fontSize: 20,
    fontWeight: 700,
    color: "var(--app-text)",
    letterSpacing: 0.2,
  },
  dialogCloseBtn: {
    color: "var(--app-text)",
    "&:hover": {
      bgcolor: "rgba(255,255,255,0.08)",
    },
  },
  dialogContent: {
    pt: 2,
    px: 3,
    pb: 2,
    display: "flex",
    flexDirection: "column",
    gap: 2.5,
    minWidth: 280,
  },
  addLanguageDialogContent: {
    pt: 2,
    px: 3,
    pb: 2,
    display: "flex",
    flexDirection: "column",
    gap: 2.5,
    minWidth: 320,
    overflow: "visible",
  },
  dialogField: {
    overflow: "visible",
    "& .MuiInputLabel-root": {
      color: "var(--app-text-muted)",
      maxWidth: "calc(100% - 8px)",
      overflow: "visible",
      whiteSpace: "nowrap",
      textOverflow: "clip",
    },
    "& .MuiOutlinedInput-notchedOutline legend": {
      maxWidth: "100%",
    },
    "& .MuiOutlinedInput-root": {
      color: "var(--app-text)",
      overflow: "visible",
      "& fieldset": {
        borderColor: "var(--app-control-border)",
      },
      "&:hover fieldset": {
        borderColor: "rgba(255,255,255,0.4)",
      },
      "&.Mui-focused fieldset": {
        borderColor: "#df4d4d",
      },
    },
    "& .MuiOutlinedInput-input, & .MuiSelect-select": {
      overflow: "visible",
      textOverflow: "clip",
    },
    "& .MuiSvgIcon-root": {
      color: "var(--app-text-muted)",
    },
  },
  dialogActions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 2,
    px: 3,
    pb: 3,
    pt: 1,
  },
  dialogCancelBtn: {
    borderRadius: 999,
    px: 4,
    py: 1.5,
    minWidth: 160,
    textTransform: "uppercase",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.6,
    color: "var(--app-text-muted)",
    borderColor: "var(--app-control-border)",
    "&:hover": {
      borderColor: "rgba(255,255,255,0.35)",
      bgcolor: "rgba(255,255,255,0.04)",
    },
  },
  dialogConfirmBtn: {
    borderRadius: 999,
    px: 4,
    py: 1.5,
    minWidth: 160,
    textTransform: "uppercase",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.6,
    bgcolor: "#df4d4d",
    color: "#fff",
    boxShadow: "none",
    "&:hover": {
      bgcolor: "#cf3d3d",
      boxShadow: "none",
    },
    "&.Mui-disabled": {
      backgroundColor: "rgba(255,255,255,0.12)",
      color: "rgba(255,255,255,0.7)",
      boxShadow: "none",
    },
    "&.Mui-disabled:hover": {
      backgroundColor: "rgba(255,255,255,0.12)",
      boxShadow: "none",
    },
  },
  bulkDeleteCountBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    width: 32,
    height: 32,
    minWidth: 32,
    maxWidth: 32,
    flexShrink: 0,
    p: 0,
    borderRadius: "50%",
    bgcolor: "#fff",
    color: "#df4d4d",
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1,
  },
  bulkDeleteToolbarBtn: {
    borderRadius: 999,
    px: 4,
    py: 1.5,
    minWidth: 160,
    textTransform: "uppercase",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.6,
    bgcolor: "#df4d4d",
    color: "#fff",
    boxShadow: "none",
    gap: 1.25,
    "&:hover": {
      bgcolor: "#cf3d3d",
      boxShadow: "none",
    },
    "&.Mui-disabled": {
      backgroundColor: "rgba(255,255,255,0.12)",
      color: "rgba(255,255,255,0.7)",
      boxShadow: "none",
    },
    "&.Mui-disabled:hover": {
      backgroundColor: "rgba(255,255,255,0.12)",
      boxShadow: "none",
    },
  },
  dialogRemoveConfirmBtn: {
    borderRadius: 999,
    px: 4,
    py: 1.5,
    minWidth: 160,
    textTransform: "uppercase",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.6,
    bgcolor: "#df4d4d",
    color: "#fff",
    boxShadow: "none",
    "&:hover": {
      bgcolor: "#cf3d3d",
      boxShadow: "none",
    },
    "&.Mui-disabled": {
      backgroundColor: "rgba(255,255,255,0.12)",
      color: "rgba(255,255,255,0.7)",
      boxShadow: "none",
    },
    "&.Mui-disabled:hover": {
      backgroundColor: "rgba(255,255,255,0.12)",
      boxShadow: "none",
    },
  },
} as const;
