export const userProfileLanguagesSx = {
  sectionTitle: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: "none",
    mb: 3,
  },
  mainColumn: {
    display: "flex",
    flexDirection: "column",
    minHeight: 280,
  },
  languagesRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    rowGap: 4,
    flex: 1,
    py: 2,
    px: { xs: 2, sm: 3 },
    listStyle: "none",
    m: 0,
  },
  languageListItem: {
    listStyle: "none",
    display: "flex",
    justifyContent: "flex-start",
  },
  languageEntryClickable: {
    margin: 0,
    gap: 3,
    font: "inherit",
    color: "inherit",
    textAlign: "left",
  },
  languageEntryStatic: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    minHeight: 48,
    height: 48,
    px: 2,
    py: 1,
    boxSizing: "border-box",
  },
  proficiencyLearner: {
    color: "#6fcf97",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  proficiencyNative: {
    color: "#df4d4d",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  languageName: {
    color: "var(--app-text-muted)",
    fontSize: 18,
    fontWeight: 400,
  },
  addLanguageBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "var(--app-text-muted)",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "var(--app-text)",
    },
  },
  removeLanguagesBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "#df4d4d",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "#ef6d6d",
    },
  },
  emptyState: {
    color: "var(--app-text-muted)",
    fontSize: 15,
    textAlign: "center",
    py: 4,
  },
  errorText: {
    color: "#ffb4b4",
    fontSize: 14,
  },
} as const;
