export const userProfileLanguagesSx = {
  sectionTitle: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: "none",
    mb: 3,
  },
  mainColumn: {
    display: "flex",
    flexDirection: "column",
    minHeight: 280,
  },
  languagesRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 6,
    rowGap: 4,
    flex: 1,
    py: 2,
    listStyle: "none",
    m: 0,
    p: 0,
  },
  languageListItem: {
    listStyle: "none",
  },
  languageEntryClickable: {
    padding: 0,
    margin: 0,
    background: "transparent",
    cursor: "pointer",
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    font: "inherit",
    color: "inherit",
    textAlign: "left",
    py: 1,
    px: 2,
    mx: -0.5,
    "&:hover": {
      bgcolor: "rgba(255,255,255,0.06)",
    },
  },
  languageEntryClickableSelected: {
    "&:hover": {
      bgcolor: "rgba(223,77,77,0.16)",
    },
  },
  languageEntryStatic: {
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    py: 1,
    px: 1.5,
  },
  proficiencyLearner: {
    color: "#6fcf97",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  proficiencyNative: {
    color: "#df4d4d",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  languageName: {
    color: "var(--app-text-muted)",
    fontSize: 18,
    fontWeight: 400,
  },
  actionsRow: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 3,
    flexWrap: "wrap",
    mt: "auto",
    pt: 3,
    pr: { xs: 4, sm: 8 },
    pl: 0,
  },
  addLanguageBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "var(--app-text-muted)",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "var(--app-text)",
    },
  },
  removeLanguagesBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "#df4d4d",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "#ef6d6d",
    },
  },
  emptyState: {
    color: "var(--app-text-muted)",
    fontSize: 15,
    textAlign: "center",
    py: 4,
  },
  errorText: {
    color: "#ffb4b4",
    fontSize: 14,
  },
} as const;
