export const userSkillsSx = {
  mainColumn: {
    display: "flex",
    flexDirection: "column",
    minHeight: 280,
  },
  categoriesStack: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    flex: 1,
  },
  categoryBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  categoryTitle: {
    color: "var(--app-text)",
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 1.4,
    m: 0,
  },
  skillsGrid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      sm: "repeat(2, minmax(0, 1fr))",
      lg: "repeat(3, minmax(0, 1fr))",
    },
    gap: 2,
    alignItems: "center",
    listStyle: "none",
    m: 0,
    p: 0,
  },
  skillListItem: {
    listStyle: "none",
    minWidth: 0,
  },
  actionsRow: {
    display: "flex",
    justifyContent: { xs: "center", sm: "flex-end" },
    alignItems: "center",
    gap: 3,
    flexWrap: "wrap",
    mt: "auto",
    pt: 4,
    pr: { xs: 0, sm: 2 },
    pl: 0,
  },
  addSkillBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "var(--app-text-muted)",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "var(--app-text)",
    },
  },
  removeSkillsBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "#df4d4d",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "#ef6d6d",
    },
  },
  bulkDeleteToolbarBtn: {
    borderRadius: 999,
    px: 4,
    py: 1.5,
    minWidth: 160,
    textTransform: "uppercase",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: 0.6,
    bgcolor: "#df4d4d",
    color: "#fff",
    boxShadow: "none",
    gap: 1.25,
    "&:hover": {
      bgcolor: "#cf3d3d",
      boxShadow: "none",
    },
    "&.Mui-disabled": {
      backgroundColor: "rgba(255,255,255,0.12)",
      color: "rgba(255,255,255,0.7)",
      boxShadow: "none",
    },
  },
  bulkDeleteCountBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    boxSizing: "border-box",
    width: 32,
    height: 32,
    minWidth: 32,
    maxWidth: 32,
    flexShrink: 0,
    p: 0,
    borderRadius: "50%",
    bgcolor: "#fff",
    color: "#df4d4d",
    fontSize: 12,
    fontWeight: 800,
    lineHeight: 1,
  },
  emptyState: {
    color: "var(--app-text-muted)",
    fontSize: 15,
    py: 2,
  },
  errorText: {
    color: "#ffb4b4",
    fontSize: 14,
  },
} as const;
