export const userLanguagesSx = {
  sectionTitle: {
    color: "var(--app-text-muted)",
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.4,
    textTransform: "none",
    mb: 3,
  },
  mainColumn: {
    display: "flex",
    flexDirection: "column",
    minHeight: 280,
  },
  languagesRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    justifyContent: "center",
    gap: 4,
    rowGap: 2,
    flex: 1,
    py: 2,
    listStyle: "none",
    m: 0,
    p: 0,
  },
  languageEntry: {
    display: "flex",
    alignItems: "baseline",
    gap: 3,
  },
  proficiencyLearner: {
    color: "#6fcf97",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  proficiencyNative: {
    color: "#df4d4d",
    fontSize: 18,
    fontWeight: 600,
    minWidth: "4.5rem",
  },
  languageName: {
    color: "var(--app-text-muted)",
    fontSize: 18,
    fontWeight: 400,
  },
  actionsRow: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 3,
    flexWrap: "wrap",
    mt: "auto",
    pt: 3,
    pr: { xs: 4, sm: 8 },
    pl: 0,
  },
  addLanguageBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "var(--app-text-muted)",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "var(--app-text)",
    },
  },
  removeLanguagesBtn: {
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.5,
    color: "#df4d4d",
    px: 0,
    minWidth: 0,
    "&:hover": {
      backgroundColor: "transparent",
      color: "#ef6d6d",
    },
  },
  emptyState: {
    color: "var(--app-text-muted)",
    fontSize: 15,
    textAlign: "center",
    py: 4,
  },
  errorText: {
    color: "#ffb4b4",
    fontSize: 14,
  },
  languageDialog: {
    "& .MuiDialog-paper": {
      bgcolor: "var(--app-surface)",
      backgroundImage: "none",
      borderRadius: 2,
      maxWidth: 440,
      width: "100%",
    },
  },
  dialogTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
    pr: 0.5,
    pt: 1,
    pb: 0.5,
  },
  dialogTitleText: {
    fontSize: 20,
    fontWeight: 700,
    color: "var(--app-text)",
    letterSpacing: 0.2,
  },
  dialogCloseBtn: {
    color: "var(--app-text)",
    "&:hover": {
      bgcolor: "rgba(255,255,255,0.08)",
    },
  },
  dialogContent: {
    pt: 2,
    px: 3,
    pb: 2,
    display: "flex",
    flexDirection: "column",
    gap: 2.5,
    minWidth: 280,
  },
  dialogField: {
    "& .MuiInputLabel-root": {
      color: "var(--app-text-muted)",
    },
    "& .MuiOutlinedInput-root": {
      color: "var(--app-text)",
      "& fieldset": {
        borderColor: "var(--app-control-border)",
      },
      "&:hover fieldset": {
        borderColor: "rgba(255,255,255,0.4)",
      },
      "&.Mui-focused fieldset": {
        borderColor: "#df4d4d",
      },
    },
    "& .MuiSvgIcon-root": {
      color: "var(--app-text-muted)",
    },
  },
  dialogActions: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 2,
    px: 3,
    pb: 3,
    pt: 1,
  },
  dialogCancelBtn: {
    borderRadius: 999,
    px: 3,
    py: 1,
    minWidth: 120,
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.6,
    color: "var(--app-text-muted)",
    borderColor: "var(--app-control-border)",
    "&:hover": {
      borderColor: "rgba(255,255,255,0.35)",
      bgcolor: "rgba(255,255,255,0.04)",
    },
  },
  dialogConfirmBtn: {
    borderRadius: 999,
    px: 3,
    py: 1,
    minWidth: 120,
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.6,
    bgcolor: "#df4d4d",
    color: "#fff",
    boxShadow: "none",
    "&:hover": {
      bgcolor: "#cf3d3d",
      boxShadow: "none",
    },
    "&.Mui-disabled": {
      bgcolor: "rgba(223,77,77,0.35)",
      color: "rgba(255,255,255,0.7)",
    },
  },
  dialogRemoveConfirmBtn: {
    borderRadius: 999,
    px: 3,
    py: 1,
    minWidth: 120,
    textTransform: "uppercase",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 0.6,
    bgcolor: "#df4d4d",
    color: "#fff",
    boxShadow: "none",
    "&:hover": {
      bgcolor: "#cf3d3d",
      boxShadow: "none",
    },
    "&.Mui-disabled": {
      bgcolor: "rgba(223,77,77,0.35)",
      color: "rgba(255,255,255,0.7)",
    },
  },
} as const;
